class gpso:
    prinatie = 'Описание'
    prinatie_pp = 'Описание'
    noans = 'Описание'
    ring = 'Описание'
    hold = 'Описание'
    acw =  'Описание'
    opros = 'Описание'
    odsat = 'Описание'
    csat = 'Описание'
    reg = 'Описание'
    test_pp = 'Описание'
    test =  'Описание'
    aht_pp = 'Описание'
    aht_not = 'Описание'
    aht = 'Описание'
    pp_ef = 'Описание'
    ko = 'Описание'